exports.BOOTSTRAP   = 'BOOTSTRAP/';

exports.SIGNIN             = 'USERS/SIGNIN';
exports.SIGNIN_SUCCESS     = 'USERS/SIGNIN:SUCCESS';
exports.SIGNIN_ERROR       = 'USERS/SIGNIN:ERROR';
exports.SIGNIN_FORM_CHANGE = 'USERS/SIGNIN:FORM_CHANGE';

exports.SIGNUP             = 'USERS/SIGNUP';
exports.SIGNUP_SUCCESS     = 'USERS/SIGNUP:SUCCESS';
exports.SIGNUP_ERROR       = 'USERS/SIGNUP:ERROR';
exports.SIGNUP_FORM_CHANGE = 'USERS/SIGNUP:FORM_CHANGE';
exports.SIGNUP_FORM_FIELD_ERROR = 'USERS/SIGNUP:FORM_FIELD_ERROR';

exports.SIGNOUT            = 'USERS/SIGNOUT';
exports.SIGNOUT_SUCCESS    = 'USERS/SIGNOUT:SUCCESS';
exports.SIGNOUT_ERROR      = 'USERS/SIGNOUT:ERROR';
exports.AUTH               = 'USERS/AUTH';
exports.AUTH_SUCCESS       = 'USERS/AUTH:SUCCESS';
exports.AUTH_ERROR         = 'USERS/AUTH:ERROR';
exports.ACTIVITY           = 'USERS/ACTIVITY';

exports.CREATE_PHONE         = 'PHONES/CREATE';
exports.CREATE_PHONE_SUCCESS = 'PHONES/CREATE:SUCCESS';
exports.CREATE_PHONE_ERROR   = 'PHONES/CREATE:ERROR';
exports.READ_PHONES          = 'PHONES/READ';
exports.READ_PHONES_SUCCESS  = 'PHONES/READ:SUCCESS';
exports.READ_PHONES_ERROR    = 'PHONES/READ:ERROR';
exports.DELETE_PHONE         = 'PHONES/DELETE';
exports.DELETE_PHONE_SUCCESS = 'PHONES/DELETE:SUCCESS';
exports.DELETE_PHONE_ERROR   = 'PHONES/DELETE:ERROR';

exports.CHECK_PHONE         = 'PHONES/CHECK';
exports.CHECK_PHONE_SUCCESS = 'PHONES/CHECK:SUCCESS';
exports.CHECK_PHONE_ERROR   = 'PHONES/CHECK:ERROR';
exports.CHECK_PHONE_CLEAR   = 'PHONES/CHECK:CLEAR';
